# Generated by Django 4.1.1 on 2023-01-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NytArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NytStable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WsjArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WsjStable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('entity', models.CharField(max_length=200)),
                ('full', models.CharField(max_length=200)),
            ],
        ),
    ]
